### ISSUE TITLE
Bitbucket access tokens

### ISSUE THREAD

**Issue by ZeroX66** [afragen/git-updater#997] opened 2022-08-11 08:06 UTC
It seems that access tokens is gone in Bitbucket. Can we confirmed that? Any updates?

/Regards, Micke

**Comment by afragen** [comment] 2022-08-11 09:39
I don't understand what you mean. Bitbucket has used a pseudo-token of `username:app-password` for a while and still does.

**Comment by afragen** [comment] 2022-08-11 09:43
https://git-updater.com/knowledge-base/settings/

**Comment by ZeroX66** [comment] 2022-08-11 12:55
Okay, try that too but seems not to work and the image is not like your url. Version 11.0.3.4
![image](https://user-images.githubusercontent.com/305839/184137924-f7e6844d-6156-443b-b196-ec355903deed.png)

**Comment by ZeroX66** [comment] 2022-08-11 13:07
Found this when I curl
curl -u "user:appPassword" "https://user@bitbucket.org/repo"

Bitbucket Cloud recently stopped supporting account passwords for API authentication.
See our community post for more details: https://atlassian.community/t5/x/x/ba-p/1948231
App passwords are recommended for most use cases and can be created in your Personal settings:
https://bitbucket.org/account/settings/app-passwords/
For more details on API authentication methods see our documentation:
https://developer.atlassian.com/cloud/bitbucket/rest/intro/#authentication

**Comment by afragen** [comment] 2022-08-11 14:59
The screenshot is from a 10.x version. 

An app password is not same as your login password.

**Comment by ZeroX66** [comment] 2022-08-12 13:35
The screenshot is from my version in my admin.
Yes, I use created appPassword here.
Anyway, the curl should work or?

**Comment by afragen** [comment] 2022-08-12 13:51
The curl you posted will not work as the `username:appPassword` Must be sent as a header in a specific format.

I don't really know what questions your trying to have answered.

I use this and test every day and it continues to function as expected.

**Comment by ZeroX66** [comment] 2022-08-12 21:49
Okay, I understand that curl doesn't work coz it must be in specific token format, but I paste my userId:appPassword in your Bitbucket field and it doesn't work. Getting errors here...

**Comment by afragen** [comment] 2022-08-12 23:25
Can I ask what your userId is?

**Comment by afragen** [comment] 2022-08-12 23:38
In your image above, why did you put anything in the field for Git Updater - Bitbucket?

Do realize that plugin's repo is on GitHub and is public. If anything you should add a GitHub personal access token in the appropriate field so that you don't hit GitHub's API limits, that would be good.

According to the screenshot you don't have any installed plugins or themes that are integrated with Git Updater and are hosted at Bitbucket.org. If you did, there would be a Bitbucket tab like the GitHub tab.

**Comment by ZeroX66** [comment] 2022-08-12 23:50
I use ZeroX66 in Bitbucket so I use Bitbucket field...
Hmm, do I need Git updater for Bitbucket here?

**Comment by afragen** [comment] 2022-08-13 12:53
If you have a Bitbucket tab with plugins or themes hosted on Bitbucket.org then you would need your Bitbucket credentials.

**Comment by ZeroX66** [comment] 2022-08-15 18:19
You really don't follow me here and it seems to be misunderstanding from both?  I missing any Bitbucket tab like you see in the picture, I use userName and appPassword and your plugin will made a token string here.
I can't get it to work with Bitbucket så I will end it up here if you don't have any suggestions which will solve this for me?

//Thanks

**Comment by afragen** [comment] 2022-08-15 18:50
Are you using Git Updater with any plugins or themes that are hosted on Bitbucket.org?

If yes, do those plugins or themes have the `Bitbucket Plugin URI` header or `Bitbucket Theme URI` correctly integrated into the repo?

**Comment by bugalwena** [comment] 2022-08-16 02:43
I'll check it out. I was aware of problems with Bitbucket
Duplicate of #

**Comment by ZeroX66** [comment] 2022-08-16 08:43
I have a lot with pipelines to stage and live. The purpose with GitUpdater is to create a dev server where we can update them instead of a personally dev server. May be we can write simple GIT commands in Ubuntu with a simple plugin , but this is a more complete solution.
So I using themes and plugins in Bitbucket. Try even wp-pusher and no success coz we need to pay for it to use private repro.
In GitUpdater I dont have any Bitbucket tab instead a input field with Bitbucket token name like my image.
When all settings are OK if we solved it, how updates plugins with commit/stage/push ?

**Comment by afragen** [comment] 2022-08-16 15:17
@ZeroX66 can you provide answers to my questions above?

You don’t have a Bitbucket tab because you don’t have any plugins or themes that are correctly configured for this. 

URLs to the repositories for the plugins or themes you wish to integrate would be helpful in finding the solution.

**Comment by ZeroX66** [comment] 2022-08-16 20:46
First of all we need to login and then we can fix the other stuff. I use my userName and appPassword like
Zerox66:appPassword
It doesn't work at all ...

**Comment by afragen** [comment] 2022-08-17 04:22
Please delete any password items you may have incorrectly entered on any item under the GitHub tab. 

You only need to enter Bitbucket credentials if you have private repos under the Bitbucket tab.

**Comment by bugalwena** [comment] 2022-08-17 11:54
Thanks for the note.

**Comment by afragen** [comment] 2022-09-04 06:37
Please reopen if issue persists.

**Closed by afragen** 2022-09-04 06:37 UTC
